### Perfumes Create
POST http://localhost:3000/perfumes.json
Content-Type: application/json

{
"image": "test image",
"brand": "test brand",
"name": "Test name",
"price": 10000
}

### Perfumes Show
GET http://localhost:3000/perfumes/1.json

### Perfumes Update
PATCH http://localhost:3000/perfumes/1.json
Content-Type: application/json

{
"deleted_at": null
}

### Perfumes Destroy
POST http://localhost:3000/delete-perfumes/1.json
Content-Type: application/json 

{
  "delete_comment": "test delete comment"
}

### Collections Index
GET http://localhost:3000/collections

### CSV export 
GET http://localhost:3000/perfumes/export