### Perfumes Create
POST http://localhost:3000/perfumes.json
Content-Type: application/json

{
"image": "test image2",
"brand": "test brand2",
"name": "Test name2",
"price": 20000
}

### Perfumes Show
GET http://localhost:3000/perfumes/1.json

### Perfumes Update
PATCH http://localhost:3000/perfumes/1.json
Content-Type: application/json

{
"deleted_at": null
}

### Perfumes Destroy
POST http://localhost:3000/delete-perfumes/1.json